### ISSUE TITLE
V BITS OF STATISTICS, Subsection "Statistics survival guide"

### ISSUE THREAD

**Issue by yeyuan98** [biostars/biostar-handbook-issues#136]
Thanks for the effort, I think I am learning a lot for the handbook. I have some suggestions to this section:

1. Seems like the data table printed is not matching the sentences in **The data** subsection. For TP53 the printed table reads `c(1887.7, 8.1, 2399.6)` for C conditions while the sentence says `c(887.7, 8.1, 1799.6)`. It's minor typo, but it looks like the numbers don't match across the "survival guide" subsection.
2. Could you explain more on the **Adjusted p-values** part? You used `p.adjust(t$p.value, n=2)` to adjust the one p-value we calculated. Why is it that you don't need to provide all of the p-values (two here)? More specifically, it doesn't look like the adjustment is `p*n`, where `n` is the number of observations. From the large table shown in the **False discovery rate** subsection, we can take two rows and compare the `PAdj` vs `PValue`. If you don't provide all p-values, what adjustment is it doing under the hood?

For the second point above, it would be great if you can provide a bit more explanation. I understand that it's not possible to explain all the details, but given my background I would like to hear more advice if possible.

**Comment by ialbert** [comment]
thanks for the report,

apologies for the typo, I modified the data a few times, looks like I forgot to make the changes everywhere. I fixed the main table, which should now match the subsequent examples. Reload the page to see the new content.

I have added an extra paragraph to the adjusted p-value section to answer your question:

---

We can adjust p-values individually, just by knowing `n` because each p-value is computed independently of all other p-values.

Note: Even though tools typically correct the p-value itself, conceptually, what should be corrected is the significance threshold. That is for `n=10` we ought to reduce a `0.05` significance level to `0.005`. Now the way p-values are typically used and for clarity's sake, in most cases tools report the p-value multiplied by the correction factor as a new column, so that the same `0.05` significance threshold can be used for both corrected and uncorrected p-values."

**Comment by yeyuan98** [comment]
Thanks for the explanation. In terms of *meta analysis* versus *adjusted p-values*, how do you determine which applies?

Let's say we did one thousand experiments on TP53 gene expression (just trying to do an extreme thought experiment). Each experiment we did three biological replicates. Let `x` be group C values and `y` be group P values.

By adjusted p-value argument, even if for each of the experiment we see `x>y` p-value to be around 0.001, adjustment would just make none significant (0.001*1000~1)! By meta analysis argument, even if we never see significant p-values in any experiment, we may end up with significance if `x>y` consistently happens. What's wrong for this application of adjusted p-value?

**Comment by ialbert** [comment]
We adjust p-values to control for all possible **alternatives**, not to control for more data. 

When we add more data we do not introduce new alternatives, for example, the genes are the same.

Another way to say it, if you have an expression matrix where rows are genes and columns are samples or replicates, the adjustment is done by the number of rows not the number of columns. If, by adding more data you add more genes as well, only then would the number for correction change.

Adding more data can raise the statistical power, so that smaller effects size that before were not statistically significant become so. That is how meta-analyses work.

**Comment by yeyuan98** [comment]
Thanks a lot for the clear explanation, I don't have further questions at this point.
