### ISSUE TITLE
Confusing writing with 3',5' ends in handbook Chapter 55.6 (pdf page 472)

### ISSUE THREAD

**Issue by ChristianKKelley** [biostars/biostar-handbook-issues#142]
In this section we are given as an example:

AAAACCCC
TTTTGGGG

And told that: 5' (right) and 3' (left).  Basic intuition would suggest the top strand (AAAACCCC) should be the reference here (ie, with respect to its left and right).  Adapters are then put on either ends

 XXXXAAAACCCCYYYY

So it appears that YYYY is the 5' adapter.  But later in the section the text states

'As the read length grows longer than the DNA fragment size, it will start running into the 3' adapter...:'
 -----------> 
AAAACCCCYYYY

Making it seem that the YYYY is actually on the 3' end, not the 5' end.  This is kind of confusing - which are the 5' and 3' ends here?

Otherwise have been enjoying the book, very clear and straight forward.

**Comment by ialbert** [comment]
Sorry about the confusion, I will reword the corresponding section. 

The directionality is best explained as an image like so:

      5' --------------> 3'

where the arrow indicates the direction that most processes that operate on a DNA take. For example DNA polymerase during transcription or the sequencing process within a sequencing instrument. But since DNA is double-stranded the in reality we simultaneously have 

    5' ---------------> 3'
    3' <--------------  5' 

for the forward and reverse strands. If a gene is encoded in the DNA then, when the DNA polymerase splits the DNA it will proceed 5' to 3',  left to right or right to left depending on which strand the gene is encoded on.

Adapters may be added to the 5' and 3' ends of each fragment, and the sequencing operates from 5' to 3' direction. I will check the exact wording I use and clear it up. Hence when the read length is short the sequencing may run into the adapter.

**Comment by ChristianKKelley** [comment]
That makes sense, thank you for the clarification!
