### ISSUE TITLE
Suggestion (Topic expansion): Microarrays & R

### ISSUE THREAD

**Issue by gaiusjaugustus** [biostars/biostar-handbook-issues#2]
I think it is appropriate, since many scientists still use microarrays (often for reasons of cost), to have sections on microarray experiments and analysis.  There is a lot of avid discussion on technologies, normalization techniques, etc that I think are important for bioinformaticians to know.

Additionally, have you considered adding any information about using R?  I noticed that your BioMart section is a TODO, and R has a good package to handle this.

With that said, thanks for the amazing book.  I'm enjoying it.

**Comment by ialbert** [comment]
The book is centered primarily on techniques I am currently involved with. Now I have been a heavy user of microarrays perhaps five years ago and I agree that they still provide a cost efficient approach to measuring certain types of signals. But I haven't  analyzed this type of data in the last few years I don't feel qualified to write that section. Perhaps if I get to work on such data and gain some first hand experience with it.

As for writing up an R that is also something that I am considering. I want to write a shorter Python oriented chapter first though, since Python is more closely related to my everyday work.

Thanks for the feedback.

**Comment by gaiusjaugustus** [comment]
Hopefully someone with recent experience will volunteer to write the microarray stuff up.

As a note I forgot to mention, given the correct R package on Bioconductor, there are already vignettes there that can guide individuals (e.g. [biomaRt package](https://bioconductor.org/packages/release/bioc/vignettes/biomaRt/inst/doc/biomaRt.html)).  This would make this easier.

I hope I can contribute one day.  Looking forward to seeing what topics develop here.  Thanks again.

**Comment by ialbert** [comment]
this will be closed as we'll probably not get to cover this subject.
