### ISSUE TITLE
Perl without perlbrew

### ISSUE THREAD

**Issue by muffinman563** [biostars/biostar-handbook-issues#35]
Hello
I am having extremely difficult time getting the efetch/esearch command to work.

As per previous discussion, i tried to uninstall perlbrew but i couldn't find an option to install perl without pearlbrew. Any link/command line for installing perl without perlbrew?

This has become a huge issue because i simply cannot move forward as this module is used often.

Thank you

**Comment by ialbert** [comment]
You should not need to have perlbrew when you use conda. Conda comes with its own perl. The problem seems to be that the two perls will conflict.

What you could probably do is look at what library is missing with perlbrew and install that. In the end the problems are just one or more missing libaries in perl

You could probably do something like:

    perlbrew install-cpanm

Then do the same with other libraries that are missing. Though I don't use perlbrew myself and would not be able to test is. But like I said the errors you are getting are an indication that some libraries are not present in Perl but that is what perlbrew was designed for.
