### ISSUE TITLE
Error running command for tools installation via conda

### ISSUE THREAD

**Issue by MirrorReaper** [biostars/biostar-handbook-issues#58]
Im getting an error when running the following command

`curl http://data.biostarhandbook.com/install/conda.txt | xargs conda install -y`

The error  `xargs: conda: No such file or directory`

I have successfully installed conda (using Bash on Windows) via 

`wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh`
`bash Miniconda3-latest-Linux-x86_64.sh`

I confirmed successful installation by typing conda.

I was also able to activate bioinfo

Please advise

**Comment by ialbert** [comment]
this is an error that would occur if conda is not activated in the shell. Here is an example:

curl http://data.biostarhandbook.com/install/conda.txt | xargs echo

versus

    curl http://data.biostarhandbook.com/install/conda.txt | xargs echos

the command `echos` is not valid and raises the error you see.

Even if conda seems to work in your environment does not always mean it was properly set (exported rather than other methods). `xargs` opens subprocesses, the variables need to be exported. 

Open a new terminal, activate the enviroment and perform the same command again, if conda is on the path it should work.

**Comment by MirrorReaper** [comment]
I already did that before posting (new terminal window) and unfortunately I get the same error.

When installing conda I accidently did not initialize Miniconda3, at the end of installation process, however I edited .bashrc file and added the following (as suggested by conda)

source /home/myusername/miniconda3/etc/profile.d/conda.sh

**Comment by ialbert** [comment]
you will need to make conda accessible in the shell. I have the following in my profile

```
# added by Miniconda3 installer
export PATH="/Users/ialbert/miniconda3/bin:$PATH"
```
I will say that I am not quite sure what the right solution to recover in your case as conda may change the way it initializes itself and this version is from last year.

What I would do is delete the miniconda installation, undo all the changes and reinstall miniconda as originally intended.

**Comment by MirrorReaper** [comment]
That is not working as well. I will delete all and start over again. Will let you know the outcome.

**Comment by MirrorReaper** [comment]
Uninstalling Miniconda did not solve the issue, so I uninstalled Ubuntu and started from the beginning, luckily it worked this time. Thanks.

**Comment by ialbert** [comment]
good to know, thanks for the update.
