### ISSUE TITLE
homebrew and Xcode Command Line Tools 

### ISSUE THREAD

**Issue by njbowen** [biostars/biostar-handbook-issues#74]
In a recent attempt to install homebrew, while going through the biostar handbook, I ran into an issue with Xcode command line tools. 

Not sure if it is somehow specific to me, looks like others have experienced it as well. 

https://discourse.brew.sh/t/new-installs-requiring-xcode-manually-installed-from-app-store/4973/4

The issue is that the current install of homebrew on 

A fully updated
macOS Mojave
Version 10.14.5
With Xcode.app installed

Homebrew install tries to reinstall command line tools, but it fails. 

The solution for me was to  install command line tools from the apple developer site. 

Command_Line_Tools_macOS_10.14_for_Xcode_10.2.dmg

https://drive.google.com/file/d/1LnwX35en00djqRFD76O3AiN1O-GXdi_h/view

Then homebrew installed correctly.

**Comment by ialbert** [comment]
Thanks for the note. 

It is a bit hard to catch these problems since these require a full reinstall from scratch - a tedious process I put myself through about a month ago.

Now, on one hand,the Homebrew install is not strictly necessary though it is generally recommended as eventually, one needs a tool not included with conda.

I will link to this issue from the handbook, and we'll observe for a few weeks. 

I expect that the homebrew installation will correct itself in the near future.

**Comment by ialbert** [comment]
The thread above reports that link to the download is:

https://download.developer.apple.com/Developer_Tools/Command_Line_Tools_macOS_10.14_for_Xcode_10.2/Command_Line_Tools_macOS_10.14_for_Xcode_10.2.dmg

**Comment by njbowen** [comment]
the apple developer link needs a developer account to download.  the google drive link above was posted by a homebrew user for download as well.

**Comment by ialbert** [comment]
I see. Good to know.

**Comment by ialbert** [comment]
The book chapter has been updated with a link to this issue:

https://www.biostarhandbook.com/setup-macos.html#setup-macos

I am hoping that the homebrew maintainers will provide the proper fix in the near future.

**Comment by njbowen** [comment]
thanks, will close this thread if ok with you.
