### ISSUE TITLE
bwa alignment

### ISSUE THREAD

**Issue by theokirkland** [biostars/biostar-handbook-issues#96]
It is not clear to me what directory the commands should be run in.
I have tried both in the refs folder and out of it.
I keep getting the error 
"$ bwa mem $REF $R1 > output.sam
[E::bwa_idx_load_from_disk] fail to locate the index files
(bioinfo) "
I have run the index command an gotten a set of files
AF086833.fa		AF086833.fa.bwt		AF086833.fa.pac
AF086833.fa.amb		AF086833.fa.fa.fa	AF086833.fa.sa
AF086833.fa.ann		AF086833.fa.fai		output.sam
The output.sam file is empty
What am I doing wrong?

**Comment by ialbert** [comment]
You are not thinking about it the right way. It is not whether you are running it inside or outside a location, 

What is the value of your REF variable? What is the value of the R1 variable? How can you tell what the values are? How would you run it if no variable was allowed? REF and R1 are simply placeholders, what value do they hold? 

You need to be able to answer these questions yourself, otherwise, you need to study the chapter again.

**Comment by theokirkland** [comment]
Thanks for the prompt response.  I found the problem.  The assignment in the book is

REF=refs/$ACC.fa

when I use REF=refs/$ACC instead, it works!!

Thanks again,

Theo

**Comment by ialbert** [comment]
glad top hear
